### ISSUE TITLE
Subghz came bits error

### ISSUE THREAD

**Issue by rmukeng** [flipperdevices/flipperzero-firmware#1659]
### Describe the bug.

I have a file with 13 bits when I try to run the file, it shows parse error this has only recently started happening 

### Reproduction

Run subghz sub file that points uses came that contains 13bits

Parse error is then shown

**Comment by ESurge** [comment]
This looks related to my issue #1641, and it was fixed in #1650 

You might need to wait for the change to be put into the next Release or Release Candidate. Alternatively, use the latest Dev build [Aug 24 - ce7b9437](https://update.flipperzero.one/builds/firmware/dev/flipper-z-f7-full-dev-24082022-ce7b9437.dfu)

**Comment by rmukeng** [comment]
I have tried what's mentioned on #1650, unfortunately this does not resolve the issue with my bits being 13

**Comment by Skorpionm** [comment]
and will not decide on the protocol for CAME or 12 or 24 bits

**Comment by rmukeng** [comment]
I am trying a sub file which shows 13bits but it just shows an unable to parse error message

**Comment by Skorpionm** [comment]
where did you get it? turning to the one who created this file

**Comment by rmukeng** [comment]
They are from

https://github.com/UberGuidoZ/Flipper/tree/main/Sub-GHz/Gates/Road_Arm_(UK)

They previously worked before the came change

**Comment by Skorpionm** [comment]
so you need to ask the question of whoever did them wrong

**Comment by rmukeng** [comment]
Thanks looks like the came protocol only supports 12bits or 24 no more no less change it to 12 or 24 and it parses fine
